title: "Gotten to the Point"
description: "A series of textbooks and notes for STEM undergraduate courses, maximizing clarity and completeness. Designed to minimize student frustration."

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: nil         # don’t let kramdown process math
  parse_block_html: true   # allow raw HTML inside markdown
  syntax_highlighter_opts:
    block:
      line_numbers: false

theme: minima
